name: MCONE-DemoGame
main: eu.mcone.demogame.DemoGame
depend: [ MCONE-BukkitCoreSystem, MCONE-GameAPI ]
authors: [ Rausgemoved, rufusmai ]
version: ${project.version}

translations:
  - demo.messages.gamestart
  - demo.items.iron_sword
  - demo.items.bow
  - demo.items.arrow